theme: jekyll-theme-cayman
title: Rainbow Clubs
description: A centralized directory for UH Manoa student clubs
github_editme_path: "https://github.com/rainbowclubs/rainbowclubs"
show_downloads: true
