theme: jekyll-theme-cayman
title: Rainbow Clubs
description: A centralized directory for UH Manoa student clubs
show_downloads: false
github:
  is_project_page: true
  repository_url: https://github.com/rainbowclubs/rainbowclubs
  app_url: rainbowclubs.meteorapp.com
